--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/InkoHX/LevelSystem
branches:
- master
projects:
  LevelSystem:
    path: ""
    libs:
      - src: InkoHX/LeveLibrary/LeveLibrary
        version: 0.0.4
...
